title: Josinon
description: Compartilhando conhecimento 
show_downloads: true
google_analytics:
theme: jekyll-theme-slate

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true
